# Generated by Django 3.2.5 on 2021-07-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='item',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
